// Generated by `cargo xtask codegen` from contract/openapi.json. Do not edit.

pub mod types {
    #![allow(clippy::doc_markdown)]
    use serde::{Deserialize, Serialize};
    use std::collections::BTreeMap;

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AchievementCheck {
        pub rank: CheckedRank,
        pub throttled: bool,
        pub unlocked: Vec<AchievementProgress>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AchievementProgress {
        pub category: AchievementProgressCategory,
        /// Stable achievement code (the catalogue only grows).
        pub code: String,
        pub percent: i64,
        pub target: i64,
        pub tier: AchievementProgressTier,
        pub unlocked: bool,
        /// When a check first recorded the unlock; null until then.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub unlocked_at: Option<String>,
        /// Progress towards target, capped at it.
        pub value: i64,
        /// XP the badge awards.
        pub xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AchievementProgressCategory {
        #[serde(rename = "watching")]
        Watching,
        #[serde(rename = "streaks")]
        Streaks,
        #[serde(rename = "explorer")]
        Explorer,
        #[serde(rename = "couch")]
        Couch,
        #[serde(rename = "meta")]
        Meta,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AchievementProgressCategory {
        pub fn as_str(self) -> &'static str {
            match self {
                AchievementProgressCategory::Watching => "watching",
                AchievementProgressCategory::Streaks => "streaks",
                AchievementProgressCategory::Explorer => "explorer",
                AchievementProgressCategory::Couch => "couch",
                AchievementProgressCategory::Meta => "meta",
                AchievementProgressCategory::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AchievementProgressCategory {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AchievementProgressTier {
        #[serde(rename = "bronze")]
        Bronze,
        #[serde(rename = "silver")]
        Silver,
        #[serde(rename = "gold")]
        Gold,
        #[serde(rename = "platinum")]
        Platinum,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AchievementProgressTier {
        pub fn as_str(self) -> &'static str {
            match self {
                AchievementProgressTier::Bronze => "bronze",
                AchievementProgressTier::Silver => "silver",
                AchievementProgressTier::Gold => "gold",
                AchievementProgressTier::Platinum => "platinum",
                AchievementProgressTier::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AchievementProgressTier {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AchievementStat {
        pub category: AchievementStatCategory,
        pub code: String,
        /// Gated off by a feature flag right now.
        pub hidden: bool,
        pub tier: AchievementStatTier,
        /// How many members hold it.
        pub unlocked: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AchievementStatCategory {
        #[serde(rename = "watching")]
        Watching,
        #[serde(rename = "streaks")]
        Streaks,
        #[serde(rename = "explorer")]
        Explorer,
        #[serde(rename = "couch")]
        Couch,
        #[serde(rename = "meta")]
        Meta,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AchievementStatCategory {
        pub fn as_str(self) -> &'static str {
            match self {
                AchievementStatCategory::Watching => "watching",
                AchievementStatCategory::Streaks => "streaks",
                AchievementStatCategory::Explorer => "explorer",
                AchievementStatCategory::Couch => "couch",
                AchievementStatCategory::Meta => "meta",
                AchievementStatCategory::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AchievementStatCategory {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AchievementStatTier {
        #[serde(rename = "bronze")]
        Bronze,
        #[serde(rename = "silver")]
        Silver,
        #[serde(rename = "gold")]
        Gold,
        #[serde(rename = "platinum")]
        Platinum,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AchievementStatTier {
        pub fn as_str(self) -> &'static str {
            match self {
                AchievementStatTier::Bronze => "bronze",
                AchievementStatTier::Silver => "silver",
                AchievementStatTier::Gold => "gold",
                AchievementStatTier::Platinum => "platinum",
                AchievementStatTier::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AchievementStatTier {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminListLibrarySort {
        #[serde(rename = "added")]
        Added,
        #[serde(rename = "name")]
        Name,
        #[serde(rename = "year")]
        Year,
        #[serde(rename = "size")]
        Size,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminListLibrarySort {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminListLibrarySort::Added => "added",
                AdminListLibrarySort::Name => "name",
                AdminListLibrarySort::Year => "year",
                AdminListLibrarySort::Size => "size",
                AdminListLibrarySort::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminListLibrarySort {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminListLibraryStatus {
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "processing")]
        Processing,
        #[serde(rename = "published")]
        Published,
        #[serde(rename = "hidden")]
        Hidden,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminListLibraryStatus {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminListLibraryStatus::Draft => "draft",
                AdminListLibraryStatus::Processing => "processing",
                AdminListLibraryStatus::Published => "published",
                AdminListLibraryStatus::Hidden => "hidden",
                AdminListLibraryStatus::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminListLibraryStatus {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminListLibraryType {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminListLibraryType {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminListLibraryType::Movie => "movie",
                AdminListLibraryType::Series => "series",
                AdminListLibraryType::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminListLibraryType {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AdminTitle {
        pub artwork: Vec<Artwork>,
        pub media_files: Vec<MediaFile>,
        pub seasons: Vec<Season>,
        pub subtitles_by_file: BTreeMap<String, Vec<Subtitle>>,
        pub title: Title,
        pub translations: BTreeMap<String, Translation>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AdminUserUpdate {
        /// Disabling an account also signs it out everywhere.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub disabled: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub display_name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub password: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub role: Option<AdminUserUpdateRole>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminUserUpdateRole {
        #[serde(rename = "admin")]
        Admin,
        #[serde(rename = "member")]
        Member,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminUserUpdateRole {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminUserUpdateRole::Admin => "admin",
                AdminUserUpdateRole::Member => "member",
                AdminUserUpdateRole::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminUserUpdateRole {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AnalyticsDay {
        pub active_users: i64,
        /// Seconds followers watched on a couch.
        pub couch_seconds: i64,
        pub day: String,
        pub video_seconds: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AnalyticsOverview {
        pub daily: Vec<AnalyticsDay>,
        pub days: i64,
        pub top_couch_titles: Vec<AnalyticsTopTitle>,
        pub top_titles: Vec<AnalyticsTopTitle>,
        pub top_users: Vec<AnalyticsTopUser>,
        pub totals: AnalyticsTotals,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AnalyticsTopTitle {
        pub kind: AnalyticsTopTitleKind,
        pub name: String,
        pub seconds: i64,
        pub slug: String,
        pub title_id: String,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AnalyticsTopTitleKind {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AnalyticsTopTitleKind {
        pub fn as_str(self) -> &'static str {
            match self {
                AnalyticsTopTitleKind::Movie => "movie",
                AnalyticsTopTitleKind::Series => "series",
                AnalyticsTopTitleKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AnalyticsTopTitleKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AnalyticsTopUser {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avatar_id: Option<String>,
        pub display_name: String,
        pub seconds: i64,
        pub user_id: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AnalyticsTotals {
        pub active_users: i64,
        /// Seconds followers watched on a couch.
        pub couch_seconds: i64,
        pub video_seconds: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ApiError {
        pub error: ErrorBody,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Artwork {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub accent: Option<String>,
        pub created_at: String,
        pub height: i64,
        pub id: String,
        pub kind: String,
        pub owner_id: String,
        pub owner_kind: String,
        pub path: String,
        pub source: String,
        pub width: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct BrowsePage {
        pub items: Vec<CardItem>,
        pub total: i64,
    }

    /// Only movies or only series; all when omitted.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum BrowseTitlesKind {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl BrowseTitlesKind {
        pub fn as_str(self) -> &'static str {
            match self {
                BrowseTitlesKind::Movie => "movie",
                BrowseTitlesKind::Series => "series",
                BrowseTitlesKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for BrowseTitlesKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    /// Ordering; newest first when omitted.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum BrowseTitlesSort {
        #[serde(rename = "added")]
        Added,
        #[serde(rename = "name")]
        Name,
        #[serde(rename = "year")]
        Year,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl BrowseTitlesSort {
        pub fn as_str(self) -> &'static str {
            match self {
                BrowseTitlesSort::Added => "added",
                BrowseTitlesSort::Name => "name",
                BrowseTitlesSort::Year => "year",
                BrowseTitlesSort::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for BrowseTitlesSort {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct BulkTitleAction {
        pub action: BulkTitleActionAction,
        pub ids: Vec<String>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum BulkTitleActionAction {
        #[serde(rename = "publish")]
        Publish,
        #[serde(rename = "hide")]
        Hide,
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "delete")]
        Delete,
        #[serde(rename = "rescan")]
        Rescan,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl BulkTitleActionAction {
        pub fn as_str(self) -> &'static str {
            match self {
                BulkTitleActionAction::Publish => "publish",
                BulkTitleActionAction::Hide => "hide",
                BulkTitleActionAction::Draft => "draft",
                BulkTitleActionAction::Delete => "delete",
                BulkTitleActionAction::Rescan => "rescan",
                BulkTitleActionAction::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for BulkTitleActionAction {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct CardItem {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_ver: Option<i64>,
        pub kind: String,
        pub name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_ver: Option<i64>,
        pub slug: String,
        pub title_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct CheckedRank {
        /// XP earned inside the current tier.
        pub into_tier: i64,
        pub next: NextRankTier,
        /// Progress through the current tier; 100 at the top tier.
        pub percent: i64,
        pub tier: RankTier,
        /// XP between this tier and the next; 0 at the top tier.
        pub tier_span: i64,
        pub xp: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ContinueItem {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_ver: Option<i64>,
        pub duration_seconds: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_id: Option<String>,
        pub episode_label: String,
        pub kind: String,
        pub name: String,
        pub playback_id: String,
        pub playback_kind: String,
        pub position_seconds: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_ver: Option<i64>,
        pub slug: String,
        pub title_id: String,
        pub updated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Credentials {
        pub password: String,
        pub username: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Episode {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub air_date: Option<String>,
        pub episode_number: i64,
        pub id: String,
        pub name: String,
        pub overview: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        pub season_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub thumb_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub thumb_ver: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct EpisodeInput {
        pub episode_number: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct EpisodeProgress {
        pub completed: bool,
        pub duration_seconds: i64,
        pub position_seconds: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct EpisodeUpdate {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_number: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ErrorBody {
        pub code: String,
        pub message: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct FeaturedItem {
        pub added_at: String,
        pub allow_random_playback: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_ver: Option<i64>,
        pub content_rating: String,
        pub genre_labels: Vec<String>,
        pub genres: Vec<String>,
        pub id: String,
        pub in_list: bool,
        pub kind: String,
        pub metadata_languages: Vec<String>,
        pub name: String,
        pub overview: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub release_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        pub slug: String,
        pub sort_name: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tmdb_id: Option<i64>,
        pub updated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Genre {
        pub id: i64,
        pub label: String,
        pub name: String,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum GetLeaderboardPeriod {
        #[serde(rename = "all")]
        All,
        #[serde(rename = "week")]
        Week,
        #[serde(rename = "month")]
        Month,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl GetLeaderboardPeriod {
        pub fn as_str(self) -> &'static str {
            match self {
                GetLeaderboardPeriod::All => "all",
                GetLeaderboardPeriod::Week => "week",
                GetLeaderboardPeriod::Month => "month",
                GetLeaderboardPeriod::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for GetLeaderboardPeriod {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Home {
        pub featured: Vec<FeaturedItem>,
        pub rows: Vec<HomeRow>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct HomeRow {
        pub continue_watching: Vec<ContinueItem>,
        pub items: Vec<CardItem>,
        pub kind: HomeRowKind,
        pub label: String,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum HomeRowKind {
        #[serde(rename = "continue_watching")]
        ContinueWatching,
        #[serde(rename = "recently_added")]
        RecentlyAdded,
        #[serde(rename = "genre")]
        Genre,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl HomeRowKind {
        pub fn as_str(self) -> &'static str {
            match self {
                HomeRowKind::ContinueWatching => "continue_watching",
                HomeRowKind::RecentlyAdded => "recently_added",
                HomeRowKind::Genre => "genre",
                HomeRowKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for HomeRowKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Leaderboard {
        /// The caller opted out, so is missing from rows.
        pub hidden: bool,
        /// The caller's own row, listed or not.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub me: Option<LeaderboardRow>,
        pub period: LeaderboardPeriod,
        pub rows: Vec<LeaderboardRow>,
        pub total: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum LeaderboardPeriod {
        #[serde(rename = "all")]
        All,
        #[serde(rename = "week")]
        Week,
        #[serde(rename = "month")]
        Month,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl LeaderboardPeriod {
        pub fn as_str(self) -> &'static str {
            match self {
                LeaderboardPeriod::All => "all",
                LeaderboardPeriod::Week => "week",
                LeaderboardPeriod::Month => "month",
                LeaderboardPeriod::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for LeaderboardPeriod {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LeaderboardRow {
        /// Achievements unlocked within the period.
        pub achievements: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avatar_id: Option<String>,
        pub display_name: String,
        pub is_self: bool,
        pub level: i64,
        pub tier_code: LeaderboardRowTierCode,
        pub username: String,
        /// Watch time within the period.
        pub watch_seconds: i64,
        pub xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum LeaderboardRowTierCode {
        #[serde(rename = "rookie")]
        Rookie,
        #[serde(rename = "remote")]
        Remote,
        #[serde(rename = "snack")]
        Snack,
        #[serde(rename = "binger")]
        Binger,
        #[serde(rename = "popcorn")]
        Popcorn,
        #[serde(rename = "marathoner")]
        Marathoner,
        #[serde(rename = "sage")]
        Sage,
        #[serde(rename = "cinephile")]
        Cinephile,
        #[serde(rename = "master")]
        Master,
        #[serde(rename = "legend")]
        Legend,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl LeaderboardRowTierCode {
        pub fn as_str(self) -> &'static str {
            match self {
                LeaderboardRowTierCode::Rookie => "rookie",
                LeaderboardRowTierCode::Remote => "remote",
                LeaderboardRowTierCode::Snack => "snack",
                LeaderboardRowTierCode::Binger => "binger",
                LeaderboardRowTierCode::Popcorn => "popcorn",
                LeaderboardRowTierCode::Marathoner => "marathoner",
                LeaderboardRowTierCode::Sage => "sage",
                LeaderboardRowTierCode::Cinephile => "cinephile",
                LeaderboardRowTierCode::Master => "master",
                LeaderboardRowTierCode::Legend => "legend",
                LeaderboardRowTierCode::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for LeaderboardRowTierCode {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LibraryPage {
        pub items: Vec<LibraryRow>,
        pub page: i64,
        pub total: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LibraryRow {
        pub added_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        pub episode_count: i64,
        pub hdr: bool,
        pub id: String,
        pub kind: String,
        pub max_height: i64,
        pub name: String,
        pub needs_prepare: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        pub season_count: i64,
        pub size_bytes: i64,
        pub slug: String,
        pub status: String,
        pub transcoded_bytes: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct MediaFile {
        pub audio_codec: String,
        pub audio_lang: String,
        pub audio_role: String,
        pub bitrate: i64,
        pub channels: i64,
        pub container: String,
        pub created_at: String,
        pub direct_play: bool,
        pub duration_seconds: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub file_mtime: Option<String>,
        pub height: i64,
        pub id: String,
        pub library_id: i64,
        pub path: String,
        pub sample_rate: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub scanned_at: Option<String>,
        pub size_bytes: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub source_deleted_at: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub title_id: Option<String>,
        pub video_codec: String,
        pub video_range: String,
        pub width: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct MemberRank {
        pub achievements: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avatar_id: Option<String>,
        pub couch_hosted: i64,
        pub display_name: String,
        pub level: i64,
        pub public: bool,
        pub tier_code: MemberRankTierCode,
        pub user_id: i64,
        pub username: String,
        pub watch_seconds: i64,
        pub xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum MemberRankTierCode {
        #[serde(rename = "rookie")]
        Rookie,
        #[serde(rename = "remote")]
        Remote,
        #[serde(rename = "snack")]
        Snack,
        #[serde(rename = "binger")]
        Binger,
        #[serde(rename = "popcorn")]
        Popcorn,
        #[serde(rename = "marathoner")]
        Marathoner,
        #[serde(rename = "sage")]
        Sage,
        #[serde(rename = "cinephile")]
        Cinephile,
        #[serde(rename = "master")]
        Master,
        #[serde(rename = "legend")]
        Legend,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl MemberRankTierCode {
        pub fn as_str(self) -> &'static str {
            match self {
                MemberRankTierCode::Rookie => "rookie",
                MemberRankTierCode::Remote => "remote",
                MemberRankTierCode::Snack => "snack",
                MemberRankTierCode::Binger => "binger",
                MemberRankTierCode::Popcorn => "popcorn",
                MemberRankTierCode::Marathoner => "marathoner",
                MemberRankTierCode::Sage => "sage",
                MemberRankTierCode::Cinephile => "cinephile",
                MemberRankTierCode::Master => "master",
                MemberRankTierCode::Legend => "legend",
                MemberRankTierCode::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for MemberRankTierCode {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct NewUser {
        /// Defaults to the username.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub display_name: Option<String>,
        pub password: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub role: Option<NewUserRole>,
        pub username: String,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum NewUserRole {
        #[serde(rename = "admin")]
        Admin,
        #[serde(rename = "member")]
        Member,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl NewUserRole {
        pub fn as_str(self) -> &'static str {
            match self {
                NewUserRole::Admin => "admin",
                NewUserRole::Member => "member",
                NewUserRole::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for NewUserRole {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct NextRankTier {
        pub code: NextRankTierCode,
        pub colour: String,
        pub level: i64,
        pub min_xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum NextRankTierCode {
        #[serde(rename = "rookie")]
        Rookie,
        #[serde(rename = "remote")]
        Remote,
        #[serde(rename = "snack")]
        Snack,
        #[serde(rename = "binger")]
        Binger,
        #[serde(rename = "popcorn")]
        Popcorn,
        #[serde(rename = "marathoner")]
        Marathoner,
        #[serde(rename = "sage")]
        Sage,
        #[serde(rename = "cinephile")]
        Cinephile,
        #[serde(rename = "master")]
        Master,
        #[serde(rename = "legend")]
        Legend,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl NextRankTierCode {
        pub fn as_str(self) -> &'static str {
            match self {
                NextRankTierCode::Rookie => "rookie",
                NextRankTierCode::Remote => "remote",
                NextRankTierCode::Snack => "snack",
                NextRankTierCode::Binger => "binger",
                NextRankTierCode::Popcorn => "popcorn",
                NextRankTierCode::Marathoner => "marathoner",
                NextRankTierCode::Sage => "sage",
                NextRankTierCode::Cinephile => "cinephile",
                NextRankTierCode::Master => "master",
                NextRankTierCode::Legend => "legend",
                NextRankTierCode::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for NextRankTierCode {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct PasswordChange {
        pub current_password: String,
        pub new_password: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Preferences {
        /// Saved display language (ISO 639-1), restored on sign-in.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub language: Option<String>,
        /// Appear on public profiles and leaderboards; absent means yes.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub public_profile: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub subtitles: Option<SubtitlePreferences>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProfileActivity {
        /// Watch seconds per day, oldest first, ending today.
        pub days: Vec<i64>,
        /// Day of days[0].
        pub from: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProfileHourBucket {
        pub hour: i64,
        pub video_seconds: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProfileTopTitle {
        pub kind: ProfileTopTitleKind,
        pub name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        pub seconds: i64,
        pub slug: String,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum ProfileTopTitleKind {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl ProfileTopTitleKind {
        pub fn as_str(self) -> &'static str {
            match self {
                ProfileTopTitleKind::Movie => "movie",
                ProfileTopTitleKind::Series => "series",
                ProfileTopTitleKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for ProfileTopTitleKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProfileTotals {
        pub active_days: i64,
        pub best_day_minutes: i64,
        pub biggest_couch: i64,
        pub couch_hosted: i64,
        pub couch_joined: i64,
        pub current_streak: i64,
        pub distinct_genres: i64,
        pub distinct_titles: i64,
        pub emoji_sent: i64,
        pub episodes_completed: i64,
        pub longest_streak: i64,
        pub movies_completed: i64,
        pub series_completed: i64,
        pub video_seconds: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProfileUpdate {
        /// Markdown; absent keeps the current bio.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub bio: Option<String>,
        pub display_name: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProfileUser {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avatar_id: Option<String>,
        /// Hex colour extracted from the banner; empty when there is none.
        pub banner_accent: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub banner_id: Option<String>,
        /// Markdown, rendered with raw HTML disabled.
        pub bio: String,
        pub display_name: String,
        pub member_since: String,
        pub username: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProgressReport {
        pub duration_seconds: i64,
        /// Set for an episode; exactly one of titleId and episodeId.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_id: Option<String>,
        pub position_seconds: i64,
        /// Set for a movie; exactly one of titleId and episodeId.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub title_id: Option<String>,
        /// Seconds actually played since the previous report (feeds analytics).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub watched_seconds: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct RankConfig {
        pub rates: RankRates,
        /// XP each tier starts at, rookie first; starts at 0 and strictly ascends.
        pub tiers: Vec<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct RankProgress {
        /// XP earned inside the current tier.
        pub into_tier: i64,
        pub next: NextRankTier,
        /// Progress through the current tier; 100 at the top tier.
        pub percent: i64,
        pub tier: RankTier,
        /// XP between this tier and the next; 0 at the top tier.
        pub tier_span: i64,
        pub xp: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct RankRates {
        /// XP per bronze achievement.
        pub bronze: i64,
        /// XP per couch session hosted.
        pub couch_host: i64,
        /// XP per couch session joined.
        pub couch_join: i64,
        /// XP per completed episode.
        pub episode: i64,
        /// XP per gold achievement.
        pub gold: i64,
        /// XP per completed movie.
        pub movie: i64,
        /// XP per platinum achievement.
        pub platinum: i64,
        /// XP per silver achievement.
        pub silver: i64,
        /// XP per minute of video watched.
        pub video_minute: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct RankTier {
        pub code: RankTierCode,
        pub colour: String,
        pub level: i64,
        pub min_xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum RankTierCode {
        #[serde(rename = "rookie")]
        Rookie,
        #[serde(rename = "remote")]
        Remote,
        #[serde(rename = "snack")]
        Snack,
        #[serde(rename = "binger")]
        Binger,
        #[serde(rename = "popcorn")]
        Popcorn,
        #[serde(rename = "marathoner")]
        Marathoner,
        #[serde(rename = "sage")]
        Sage,
        #[serde(rename = "cinephile")]
        Cinephile,
        #[serde(rename = "master")]
        Master,
        #[serde(rename = "legend")]
        Legend,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl RankTierCode {
        pub fn as_str(self) -> &'static str {
            match self {
                RankTierCode::Rookie => "rookie",
                RankTierCode::Remote => "remote",
                RankTierCode::Snack => "snack",
                RankTierCode::Binger => "binger",
                RankTierCode::Popcorn => "popcorn",
                RankTierCode::Marathoner => "marathoner",
                RankTierCode::Sage => "sage",
                RankTierCode::Cinephile => "cinephile",
                RankTierCode::Master => "master",
                RankTierCode::Legend => "legend",
                RankTierCode::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for RankTierCode {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct RanksOverview {
        pub achievements: Vec<AchievementStat>,
        pub average_level: f64,
        pub config: RankConfig,
        pub members: i64,
        pub rows: Vec<MemberRank>,
        pub tiers: Vec<TierBucket>,
        pub total_unlocks: i64,
        pub total_xp: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct SearchResults {
        pub titles: Vec<CardItem>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Season {
        pub episodes: Vec<Episode>,
        pub id: String,
        pub name: String,
        pub overview: String,
        pub season_number: i64,
        pub title_id: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct SeasonInput {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        pub season_number: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct StorageSegment {
        pub label: String,
        pub source_bytes: i64,
        pub transcoded_bytes: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Subtitle {
        pub created_at: String,
        pub forced: bool,
        pub id: String,
        pub label: String,
        pub lang: String,
        pub media_file_id: String,
        pub source: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct SubtitlePreferences {
        /// Opacity of the box behind the text, in percent.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub background_opacity: Option<i64>,
        /// Text colour as #rrggbb.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub color: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub font_family: Option<SubtitlePreferencesFontFamily>,
        /// Text size as a percentage of the default.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub font_size_pct: Option<i64>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum SubtitlePreferencesFontFamily {
        #[serde(rename = "sans")]
        Sans,
        #[serde(rename = "serif")]
        Serif,
        #[serde(rename = "mono")]
        Mono,
        #[serde(rename = "rounded")]
        Rounded,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl SubtitlePreferencesFontFamily {
        pub fn as_str(self) -> &'static str {
            match self {
                SubtitlePreferencesFontFamily::Sans => "sans",
                SubtitlePreferencesFontFamily::Serif => "serif",
                SubtitlePreferencesFontFamily::Mono => "mono",
                SubtitlePreferencesFontFamily::Rounded => "rounded",
                SubtitlePreferencesFontFamily::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for SubtitlePreferencesFontFamily {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TierBucket {
        pub code: TierBucketCode,
        pub colour: String,
        pub level: i64,
        pub members: i64,
        pub min_xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum TierBucketCode {
        #[serde(rename = "rookie")]
        Rookie,
        #[serde(rename = "remote")]
        Remote,
        #[serde(rename = "snack")]
        Snack,
        #[serde(rename = "binger")]
        Binger,
        #[serde(rename = "popcorn")]
        Popcorn,
        #[serde(rename = "marathoner")]
        Marathoner,
        #[serde(rename = "sage")]
        Sage,
        #[serde(rename = "cinephile")]
        Cinephile,
        #[serde(rename = "master")]
        Master,
        #[serde(rename = "legend")]
        Legend,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl TierBucketCode {
        pub fn as_str(self) -> &'static str {
            match self {
                TierBucketCode::Rookie => "rookie",
                TierBucketCode::Remote => "remote",
                TierBucketCode::Snack => "snack",
                TierBucketCode::Binger => "binger",
                TierBucketCode::Popcorn => "popcorn",
                TierBucketCode::Marathoner => "marathoner",
                TierBucketCode::Sage => "sage",
                TierBucketCode::Cinephile => "cinephile",
                TierBucketCode::Master => "master",
                TierBucketCode::Legend => "legend",
                TierBucketCode::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for TierBucketCode {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Title {
        pub added_at: String,
        pub allow_random_playback: bool,
        pub content_rating: String,
        pub genre_labels: Vec<String>,
        pub genres: Vec<String>,
        pub id: String,
        pub kind: String,
        pub metadata_languages: Vec<String>,
        pub name: String,
        pub overview: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub release_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        pub slug: String,
        pub sort_name: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tmdb_id: Option<i64>,
        pub updated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleDetail {
        pub artwork: Vec<Artwork>,
        pub episode_progress: BTreeMap<String, EpisodeProgress>,
        pub in_watchlist: bool,
        pub media_files: Vec<MediaFile>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub progress: Option<EpisodeProgress>,
        pub seasons: Vec<Season>,
        pub title: Title,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleInput {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub content_rating: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub genres: Option<Vec<String>>,
        pub kind: TitleInputKind,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub metadata_languages: Option<Vec<String>>,
        pub name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum TitleInputKind {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl TitleInputKind {
        pub fn as_str(self) -> &'static str {
            match self {
                TitleInputKind::Movie => "movie",
                TitleInputKind::Series => "series",
                TitleInputKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for TitleInputKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleStorageBreakdown {
        pub items: Vec<StorageSegment>,
        pub source_bytes: i64,
        pub transcoded_bytes: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleUpdate {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub allow_random_playback: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub content_rating: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub genres: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub metadata_languages: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub sort_name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub status: Option<TitleUpdateStatus>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tmdb_id: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum TitleUpdateStatus {
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "processing")]
        Processing,
        #[serde(rename = "published")]
        Published,
        #[serde(rename = "hidden")]
        Hidden,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl TitleUpdateStatus {
        pub fn as_str(self) -> &'static str {
            match self {
                TitleUpdateStatus::Draft => "draft",
                TitleUpdateStatus::Processing => "processing",
                TitleUpdateStatus::Published => "published",
                TitleUpdateStatus::Hidden => "hidden",
                TitleUpdateStatus::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for TitleUpdateStatus {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Translation {
        pub name: String,
        pub overview: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct User {
        /// Artwork id of the profile picture.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avatar_id: Option<String>,
        /// Artwork id of the profile banner.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub banner_id: Option<String>,
        /// Markdown, rendered with raw HTML disabled.
        pub bio: String,
        pub created_at: String,
        pub disabled: bool,
        pub display_name: String,
        pub id: i64,
        pub role: UserRole,
        pub username: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct UserProfile {
        pub achievements: Vec<AchievementProgress>,
        pub achievements_won: i64,
        pub activity: ProfileActivity,
        /// Most watched genre's label in the display language; empty when none.
        pub favourite_genre: String,
        /// Watch time by hour of day, always 24 entries.
        pub hours: Vec<ProfileHourBucket>,
        pub is_self: bool,
        /// Whether the member appears on public profiles and leaderboards.
        pub public: bool,
        pub rank: RankProgress,
        /// Newest unlocked achievements first.
        pub recent_unlocks: Vec<AchievementProgress>,
        pub top_titles: Vec<ProfileTopTitle>,
        pub totals: ProfileTotals,
        pub user: ProfileUser,
        pub xp: XpResult,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum UserRole {
        #[serde(rename = "admin")]
        Admin,
        #[serde(rename = "member")]
        Member,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl UserRole {
        pub fn as_str(self) -> &'static str {
            match self {
                UserRole::Admin => "admin",
                UserRole::Member => "member",
                UserRole::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for UserRole {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct XpResult {
        pub sources: Vec<XpSource>,
        pub total: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct XpSource {
        pub key: XpSourceKey,
        /// XP per unit; 0 for achievements, whose reward varies by tier.
        pub rate: i64,
        pub units: i64,
        pub xp: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum XpSourceKey {
        #[serde(rename = "video")]
        Video,
        #[serde(rename = "movies")]
        Movies,
        #[serde(rename = "episodes")]
        Episodes,
        #[serde(rename = "couchHosted")]
        CouchHosted,
        #[serde(rename = "couchJoined")]
        CouchJoined,
        #[serde(rename = "achievements")]
        Achievements,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl XpSourceKey {
        pub fn as_str(self) -> &'static str {
            match self {
                XpSourceKey::Video => "video",
                XpSourceKey::Movies => "movies",
                XpSourceKey::Episodes => "episodes",
                XpSourceKey::CouchHosted => "couchHosted",
                XpSourceKey::CouchJoined => "couchJoined",
                XpSourceKey::Achievements => "achievements",
                XpSourceKey::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for XpSourceKey {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }
}

pub mod ops {
    #![allow(clippy::doc_markdown, clippy::too_many_lines, clippy::wildcard_imports)]
    use super::types::*;
    use crate::{Call, Method, NoContent, Request, build};
    use std::collections::BTreeMap;

    /// `PUT /me/watchlist/{titleId}`
    pub fn add_to_watchlist(title_id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Put,
            format!("/me/watchlist/{}", build::segment(title_id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/uploads/{id}`
    pub fn admin_abort_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/uploads/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PUT /admin/uploads/{id}`
    pub fn admin_append_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Put,
            "/admin/uploads/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/titles/{id}/metadata/apply`
    pub fn admin_apply_metadata() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/titles/{id}/metadata/apply".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/titles/bulk`
    pub fn admin_bulk_titles(body: &BulkTitleAction) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Post,
            "/admin/titles/bulk".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/jobs/{id}/cancel`
    pub fn admin_cancel_job() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/jobs/{id}/cancel".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/uploads/{id}/complete`
    pub fn admin_complete_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/uploads/{id}/complete".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/seasons/{id}/episodes`
    pub fn admin_create_episode(id: &str, body: &EpisodeInput) -> Call<Episode> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            format!("/admin/seasons/{}/episodes", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/titles/{id}/seasons`
    pub fn admin_create_season(id: &str, body: &SeasonInput) -> Call<Season> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            format!("/admin/titles/{}/seasons", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/titles`
    pub fn admin_create_title(body: &TitleInput) -> Call<Title> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/admin/titles".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/uploads`
    pub fn admin_create_upload() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/admin/uploads".to_string(), q, None::<&()>)
    }

    /// `POST /admin/users`
    pub fn admin_create_user(body: &NewUser) -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/admin/users".to_string(),
            q,
            Some(body),
        ))
    }

    /// `DELETE /admin/artwork/{id}`
    pub fn admin_delete_artwork() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/artwork/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/episodes/{id}`
    pub fn admin_delete_episode(id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/episodes/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/media-files/{id}`
    pub fn admin_delete_media_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/media-files/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/seasons/{id}`
    pub fn admin_delete_season(id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/seasons/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/subtitles/{id}`
    pub fn admin_delete_subtitle() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/subtitles/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/titles/{id}`
    pub fn admin_delete_title(id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/titles/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/titles/{id}/languages/{lang}`
    pub fn admin_delete_title_language(id: &str, lang: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!(
                "/admin/titles/{}/languages/{}",
                build::segment(id),
                build::segment(lang)
            ),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/users/{id}`
    pub fn admin_delete_user(id: i64) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/users/{}", build::segment(&id.to_string())),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/transcode-variants/{id}`
    pub fn admin_delete_variant() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/transcode-variants/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/media-files/{id}/transcode`
    pub fn admin_enqueue_transcode() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/media-files/{id}/transcode".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`admin_get_analytics`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct AdminGetAnalyticsQuery {
        /// Window in days ending today, clamped to 1..365.
        pub days: Option<i64>,
    }

    /// `GET /admin/analytics/overview`
    pub fn admin_get_analytics(query: &AdminGetAnalyticsQuery) -> Call<AnalyticsOverview> {
        let mut q = Vec::new();
        build::push(&mut q, "days", query.days.as_ref());
        build::json(build::request(
            Method::Get,
            "/admin/analytics/overview".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/episodes/{id}/translations`
    pub fn admin_get_episode_translations(id: &str) -> Call<BTreeMap<String, Translation>> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            format!("/admin/episodes/{}/translations", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/home-rows`
    pub fn admin_get_home_rows() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/home-rows".to_string(), q, None::<&()>)
    }

    /// `GET /admin/live`
    pub fn admin_get_live() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/live".to_string(), q, None::<&()>)
    }

    /// `GET /admin/overview`
    pub fn admin_get_overview() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/overview".to_string(), q, None::<&()>)
    }

    /// `GET /admin/ranks`
    pub fn admin_get_ranks() -> Call<RanksOverview> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            "/admin/ranks".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/settings`
    pub fn admin_get_settings() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/settings".to_string(), q, None::<&()>)
    }

    /// `GET /admin/storage`
    pub fn admin_get_storage() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/storage".to_string(), q, None::<&()>)
    }

    /// `GET /admin/system`
    pub fn admin_get_system_stats() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/system".to_string(), q, None::<&()>)
    }

    /// `GET /admin/titles/{id}`
    pub fn admin_get_title(id: &str) -> Call<AdminTitle> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            format!("/admin/titles/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/titles/{id}/storage`
    pub fn admin_get_title_storage(id: &str) -> Call<TitleStorageBreakdown> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            format!("/admin/titles/{}/storage", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/transcode/info`
    pub fn admin_get_transcode_info() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/transcode/info".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/uploads/{id}`
    pub fn admin_get_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/uploads/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/titles/{id}/metadata/import-episodes`
    pub fn admin_import_episodes() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/titles/{id}/metadata/import-episodes".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/transcode/active`
    pub fn admin_list_active_transcodes() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/transcode/active".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/jobs`
    pub fn admin_list_jobs() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/jobs".to_string(), q, None::<&()>)
    }

    /// Query parameters of [`admin_list_library`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct AdminListLibraryQuery {
        pub r#type: Option<AdminListLibraryType>,
        pub status: Option<AdminListLibraryStatus>,
        pub q: Option<String>,
        pub sort: Option<AdminListLibrarySort>,
        pub page: Option<i64>,
        pub page_size: Option<i64>,
    }

    /// `GET /admin/library`
    pub fn admin_list_library(query: &AdminListLibraryQuery) -> Call<LibraryPage> {
        let mut q = Vec::new();
        build::push(&mut q, "type", query.r#type.as_ref());
        build::push(&mut q, "status", query.status.as_ref());
        build::push(&mut q, "q", query.q.as_ref());
        build::push(&mut q, "sort", query.sort.as_ref());
        build::push(&mut q, "page", query.page.as_ref());
        build::push(&mut q, "pageSize", query.page_size.as_ref());
        build::json(build::request(
            Method::Get,
            "/admin/library".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/titles/{id}/metadata/seasons`
    pub fn admin_list_metadata_seasons() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/titles/{id}/metadata/seasons".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/media-files/{id}/subtitles`
    pub fn admin_list_subtitles() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/media-files/{id}/subtitles".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/uploads`
    pub fn admin_list_uploads() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/uploads".to_string(), q, None::<&()>)
    }

    /// `GET /admin/users`
    pub fn admin_list_users() -> Call<Vec<User>> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            "/admin/users".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/media-files/{id}/variants`
    pub fn admin_list_variants() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/media-files/{id}/variants".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/jobs/{id}/retry`
    pub fn admin_retry_job() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/jobs/{id}/retry".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/metadata/search`
    pub fn admin_search_metadata() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/metadata/search".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PATCH /admin/episodes/{id}/translations/{lang}`
    pub fn admin_set_episode_translation(
        id: &str,
        lang: &str,
        body: &Translation,
    ) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Patch,
            format!(
                "/admin/episodes/{}/translations/{}",
                build::segment(id),
                build::segment(lang)
            ),
            q,
            Some(body),
        ))
    }

    /// `PATCH /admin/titles/{id}/translations/{lang}`
    pub fn admin_set_title_translation(
        id: &str,
        lang: &str,
        body: &Translation,
    ) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Patch,
            format!(
                "/admin/titles/{}/translations/{}",
                build::segment(id),
                build::segment(lang)
            ),
            q,
            Some(body),
        ))
    }

    /// `PATCH /admin/episodes/{id}`
    pub fn admin_update_episode(id: &str, body: &EpisodeUpdate) -> Call<Episode> {
        let q = Vec::new();
        build::json(build::request(
            Method::Patch,
            format!("/admin/episodes/{}", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `PUT /admin/home-rows`
    pub fn admin_update_home_rows() -> Request {
        let q = Vec::new();
        build::request(Method::Put, "/admin/home-rows".to_string(), q, None::<&()>)
    }

    /// `PATCH /admin/media-files/{id}`
    pub fn admin_update_media_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Patch,
            "/admin/media-files/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PUT /admin/ranks/config`
    pub fn admin_update_ranks_config(body: &RankConfig) -> Call<RankConfig> {
        let q = Vec::new();
        build::json(build::request(
            Method::Put,
            "/admin/ranks/config".to_string(),
            q,
            Some(body),
        ))
    }

    /// `PUT /admin/settings`
    pub fn admin_update_settings() -> Request {
        let q = Vec::new();
        build::request(Method::Put, "/admin/settings".to_string(), q, None::<&()>)
    }

    /// `PATCH /admin/titles/{id}`
    pub fn admin_update_title(id: &str, body: &TitleUpdate) -> Call<Title> {
        let q = Vec::new();
        build::json(build::request(
            Method::Patch,
            format!("/admin/titles/{}", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `PATCH /admin/users/{id}`
    pub fn admin_update_user(id: i64, body: &AdminUserUpdate) -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Patch,
            format!("/admin/users/{}", build::segment(&id.to_string())),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/artwork`
    pub fn admin_upload_artwork() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/admin/artwork".to_string(), q, None::<&()>)
    }

    /// `POST /admin/media-files/{id}/subtitles`
    pub fn admin_upload_subtitle() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/media-files/{id}/subtitles".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`browse_titles`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct BrowseTitlesQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
        /// Only movies or only series; all when omitted.
        pub kind: Option<BrowseTitlesKind>,
        /// English genre name (the genre's stable identity).
        pub genre: Option<String>,
        /// Case-insensitive name filter.
        pub q: Option<String>,
        /// Ordering; newest first when omitted.
        pub sort: Option<BrowseTitlesSort>,
        pub page: Option<i64>,
    }

    /// `GET /titles`
    pub fn browse_titles(query: &BrowseTitlesQuery) -> Call<BrowsePage> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::push(&mut q, "kind", query.kind.as_ref());
        build::push(&mut q, "genre", query.genre.as_ref());
        build::push(&mut q, "q", query.q.as_ref());
        build::push(&mut q, "sort", query.sort.as_ref());
        build::push(&mut q, "page", query.page.as_ref());
        build::json(build::request(
            Method::Get,
            "/titles".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `PATCH /me/password`
    pub fn change_password(body: &PasswordChange) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Patch,
            "/me/password".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /me/achievements/check`
    pub fn check_achievements() -> Call<AchievementCheck> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/me/achievements/check".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /couch/{token}/ws`
    pub fn couch_socket() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/couch/{token}/ws".to_string(), q, None::<&()>)
    }

    /// `POST /couch`
    pub fn create_couch() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/couch".to_string(), q, None::<&()>)
    }

    /// `POST /stream/{id}/sessions`
    pub fn create_stream_session() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/stream/{id}/sessions".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /me/avatar`
    pub fn delete_avatar() -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Delete,
            "/me/avatar".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /me/banner`
    pub fn delete_banner() -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Delete,
            "/me/banner".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `POST /couch/{token}/end`
    pub fn end_couch() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/couch/{token}/end".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /artwork/{id}`
    pub fn get_artwork() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/artwork/{id}".to_string(), q, None::<&()>)
    }

    /// `GET /couch/{token}/info`
    pub fn get_couch_info() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/couch/{token}/info".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /couch/{token}/playback`
    pub fn get_couch_playback() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/couch/{token}/playback".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /features`
    pub fn get_features() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/features".to_string(), q, None::<&()>)
    }

    /// `GET /stream/{id}/hls/{variant}/{file}`
    pub fn get_hls_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/{id}/hls/{variant}/{file}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /stream/{id}/hls/master.m3u8`
    pub fn get_hls_master() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/{id}/hls/master.m3u8".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`get_home`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetHomeQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /home`
    pub fn get_home(query: &GetHomeQuery) -> Call<Home> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/home".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`get_leaderboard`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetLeaderboardQuery {
        pub period: Option<GetLeaderboardPeriod>,
    }

    /// `GET /leaderboard`
    pub fn get_leaderboard(query: &GetLeaderboardQuery) -> Call<Leaderboard> {
        let mut q = Vec::new();
        build::push(&mut q, "period", query.period.as_ref());
        build::json(build::request(
            Method::Get,
            "/leaderboard".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /auth/me`
    pub fn get_me() -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            "/auth/me".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`get_my_stats`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetMyStatsQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /me/stats`
    pub fn get_my_stats(query: &GetMyStatsQuery) -> Call<UserProfile> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/me/stats".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /playback/{kind}/{id}`
    pub fn get_playback() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/playback/{kind}/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /me/preferences`
    pub fn get_preferences() -> Call<Preferences> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            "/me/preferences".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`get_profile`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetProfileQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /users/{username}/profile`
    pub fn get_profile(username: &str, query: &GetProfileQuery) -> Call<UserProfile> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            format!("/users/{}/profile", build::segment(username)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /stream/{id}/frame`
    pub fn get_stream_frame() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/{id}/frame".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /stream/sessions/{sid}/{file}`
    pub fn get_stream_session_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/sessions/{sid}/{file}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /subtitles/{id}.vtt`
    pub fn get_subtitle() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/subtitles/{id}.vtt".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /theme`
    pub fn get_theme() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/theme".to_string(), q, None::<&()>)
    }

    /// Query parameters of [`get_title`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetTitleQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /titles/{slug}`
    pub fn get_title(slug: &str, query: &GetTitleQuery) -> Call<TitleDetail> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            format!("/titles/{}", build::segment(slug)),
            q,
            None::<&()>,
        ))
    }

    /// `POST /couch/{token}/join`
    pub fn join_couch() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/couch/{token}/join".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /stream/sessions/{sid}/keepalive`
    pub fn keep_stream_session_alive() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/stream/sessions/{sid}/keepalive".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /couch/{token}/leave`
    pub fn leave_couch() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/couch/{token}/leave".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`list_continue_watching`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct ListContinueWatchingQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /me/continue-watching`
    pub fn list_continue_watching(query: &ListContinueWatchingQuery) -> Call<Vec<ContinueItem>> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/me/continue-watching".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`list_genres`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct ListGenresQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /genres`
    pub fn list_genres(query: &ListGenresQuery) -> Call<Vec<Genre>> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/genres".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`list_watchlist`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct ListWatchlistQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /me/watchlist`
    pub fn list_watchlist(query: &ListWatchlistQuery) -> Call<Vec<CardItem>> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/me/watchlist".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `POST /auth/login`
    pub fn login(body: &Credentials) -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/auth/login".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /auth/logout`
    pub fn logout() -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Post,
            "/auth/logout".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /me/watchlist/{titleId}`
    pub fn remove_from_watchlist(title_id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/me/watchlist/{}", build::segment(title_id)),
            q,
            None::<&()>,
        ))
    }

    /// `PUT /progress`
    pub fn save_progress(body: &ProgressReport) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Put,
            "/progress".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /progress`
    pub fn save_progress_beacon(body: &ProgressReport) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Post,
            "/progress".to_string(),
            q,
            Some(body),
        ))
    }

    /// Query parameters of [`search`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct SearchQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
        pub q: Option<String>,
    }

    /// `GET /search`
    pub fn search(query: &SearchQuery) -> Call<SearchResults> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::push(&mut q, "q", query.q.as_ref());
        build::json(build::request(
            Method::Get,
            "/search".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /stream/{id}`
    pub fn stream_media_file() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/stream/{id}".to_string(), q, None::<&()>)
    }

    /// `PUT /me/preferences`
    pub fn update_preferences(body: &Preferences) -> Call<Preferences> {
        let q = Vec::new();
        build::json(build::request(
            Method::Put,
            "/me/preferences".to_string(),
            q,
            Some(body),
        ))
    }

    /// `PATCH /me/profile`
    pub fn update_profile(body: &ProfileUpdate) -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Patch,
            "/me/profile".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /me/avatar`
    pub fn upload_avatar() -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/me/avatar".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `POST /me/banner`
    pub fn upload_banner() -> Call<User> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/me/banner".to_string(),
            q,
            None::<&()>,
        ))
    }
}
