// Generated by `cargo xtask codegen` from contract/openapi.json. Do not edit.

pub mod types {
    #![allow(clippy::doc_markdown)]
    use serde::{Deserialize, Serialize};
    use std::collections::BTreeMap;

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminListLibrarySort {
        #[serde(rename = "added")]
        Added,
        #[serde(rename = "name")]
        Name,
        #[serde(rename = "year")]
        Year,
        #[serde(rename = "size")]
        Size,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminListLibrarySort {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminListLibrarySort::Added => "added",
                AdminListLibrarySort::Name => "name",
                AdminListLibrarySort::Year => "year",
                AdminListLibrarySort::Size => "size",
                AdminListLibrarySort::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminListLibrarySort {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminListLibraryStatus {
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "processing")]
        Processing,
        #[serde(rename = "published")]
        Published,
        #[serde(rename = "hidden")]
        Hidden,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminListLibraryStatus {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminListLibraryStatus::Draft => "draft",
                AdminListLibraryStatus::Processing => "processing",
                AdminListLibraryStatus::Published => "published",
                AdminListLibraryStatus::Hidden => "hidden",
                AdminListLibraryStatus::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminListLibraryStatus {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum AdminListLibraryType {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl AdminListLibraryType {
        pub fn as_str(self) -> &'static str {
            match self {
                AdminListLibraryType::Movie => "movie",
                AdminListLibraryType::Series => "series",
                AdminListLibraryType::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for AdminListLibraryType {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct AdminTitle {
        pub artwork: Vec<Artwork>,
        pub media_files: Vec<MediaFile>,
        pub seasons: Vec<Season>,
        pub subtitles_by_file: BTreeMap<String, Vec<Subtitle>>,
        pub title: Title,
        pub translations: BTreeMap<String, Translation>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ApiError {
        pub error: ErrorBody,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Artwork {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub accent: Option<String>,
        pub created_at: String,
        pub height: i64,
        pub id: String,
        pub kind: String,
        pub owner_id: String,
        pub owner_kind: String,
        pub path: String,
        pub source: String,
        pub width: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct BrowsePage {
        pub items: Vec<CardItem>,
        pub total: i64,
    }

    /// Only movies or only series; all when omitted.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum BrowseTitlesKind {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl BrowseTitlesKind {
        pub fn as_str(self) -> &'static str {
            match self {
                BrowseTitlesKind::Movie => "movie",
                BrowseTitlesKind::Series => "series",
                BrowseTitlesKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for BrowseTitlesKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    /// Ordering; newest first when omitted.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum BrowseTitlesSort {
        #[serde(rename = "added")]
        Added,
        #[serde(rename = "name")]
        Name,
        #[serde(rename = "year")]
        Year,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl BrowseTitlesSort {
        pub fn as_str(self) -> &'static str {
            match self {
                BrowseTitlesSort::Added => "added",
                BrowseTitlesSort::Name => "name",
                BrowseTitlesSort::Year => "year",
                BrowseTitlesSort::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for BrowseTitlesSort {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct BulkInputBody {
        pub action: BulkInputBodyAction,
        pub ids: Vec<String>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum BulkInputBodyAction {
        #[serde(rename = "publish")]
        Publish,
        #[serde(rename = "hide")]
        Hide,
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "delete")]
        Delete,
        #[serde(rename = "rescan")]
        Rescan,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl BulkInputBodyAction {
        pub fn as_str(self) -> &'static str {
            match self {
                BulkInputBodyAction::Publish => "publish",
                BulkInputBodyAction::Hide => "hide",
                BulkInputBodyAction::Draft => "draft",
                BulkInputBodyAction::Delete => "delete",
                BulkInputBodyAction::Rescan => "rescan",
                BulkInputBodyAction::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for BulkInputBodyAction {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct CardItem {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_ver: Option<i64>,
        pub kind: String,
        pub name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_ver: Option<i64>,
        pub slug: String,
        pub title_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ContinueItem {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_ver: Option<i64>,
        pub duration_seconds: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_id: Option<String>,
        pub episode_label: String,
        pub kind: String,
        pub name: String,
        pub playback_id: String,
        pub playback_kind: String,
        pub position_seconds: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_ver: Option<i64>,
        pub slug: String,
        pub title_id: String,
        pub updated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct CreateSeasonInputBody {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        pub season_number: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Episode {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub air_date: Option<String>,
        pub episode_number: i64,
        pub id: String,
        pub name: String,
        pub overview: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        pub season_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub thumb_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub thumb_ver: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct EpisodeInput {
        pub episode_number: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct EpisodeProgress {
        pub completed: bool,
        pub duration_seconds: i64,
        pub position_seconds: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct EpisodeUpdate {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_number: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ErrorBody {
        pub code: String,
        pub message: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct FeaturedItem {
        pub added_at: String,
        pub allow_random_playback: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_accent: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_ver: Option<i64>,
        pub content_rating: String,
        pub genre_labels: Vec<String>,
        pub genres: Vec<String>,
        pub id: String,
        pub in_list: bool,
        pub kind: String,
        pub metadata_languages: Vec<String>,
        pub name: String,
        pub overview: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub release_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        pub slug: String,
        pub sort_name: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tmdb_id: Option<i64>,
        pub updated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Genre {
        pub id: i64,
        pub label: String,
        pub name: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Home {
        pub featured: Vec<FeaturedItem>,
        pub rows: Vec<HomeRow>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct HomeRow {
        pub continue_watching: Vec<ContinueItem>,
        pub items: Vec<CardItem>,
        pub kind: HomeRowKind,
        pub label: String,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum HomeRowKind {
        #[serde(rename = "continue_watching")]
        ContinueWatching,
        #[serde(rename = "recently_added")]
        RecentlyAdded,
        #[serde(rename = "genre")]
        Genre,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl HomeRowKind {
        pub fn as_str(self) -> &'static str {
            match self {
                HomeRowKind::ContinueWatching => "continue_watching",
                HomeRowKind::RecentlyAdded => "recently_added",
                HomeRowKind::Genre => "genre",
                HomeRowKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for HomeRowKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LibraryPage {
        pub items: Vec<LibraryRow>,
        pub page: i64,
        pub total: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LibraryRow {
        pub added_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub backdrop_id: Option<String>,
        pub episode_count: i64,
        pub hdr: bool,
        pub id: String,
        pub kind: String,
        pub max_height: i64,
        pub name: String,
        pub needs_prepare: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub poster_id: Option<String>,
        pub season_count: i64,
        pub size_bytes: i64,
        pub slug: String,
        pub status: String,
        pub transcoded_bytes: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct MediaFile {
        pub audio_codec: String,
        pub audio_lang: String,
        pub audio_role: String,
        pub bitrate: i64,
        pub channels: i64,
        pub container: String,
        pub created_at: String,
        pub direct_play: bool,
        pub duration_seconds: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub file_mtime: Option<String>,
        pub height: i64,
        pub id: String,
        pub library_id: i64,
        pub path: String,
        pub sample_rate: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub scanned_at: Option<String>,
        pub size_bytes: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub source_deleted_at: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub title_id: Option<String>,
        pub video_codec: String,
        pub video_range: String,
        pub width: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ProgressReport {
        pub duration_seconds: i64,
        /// Set for an episode; exactly one of titleId and episodeId.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub episode_id: Option<String>,
        pub position_seconds: i64,
        /// Set for a movie; exactly one of titleId and episodeId.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub title_id: Option<String>,
        /// Seconds actually played since the previous report (feeds analytics).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub watched_seconds: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct SearchResults {
        pub titles: Vec<CardItem>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Season {
        pub episodes: Vec<Episode>,
        pub id: String,
        pub name: String,
        pub overview: String,
        pub season_number: i64,
        pub title_id: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct StorageSegment {
        pub label: String,
        pub source_bytes: i64,
        pub transcoded_bytes: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Subtitle {
        pub created_at: String,
        pub forced: bool,
        pub id: String,
        pub label: String,
        pub lang: String,
        pub media_file_id: String,
        pub source: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Title {
        pub added_at: String,
        pub allow_random_playback: bool,
        pub content_rating: String,
        pub genre_labels: Vec<String>,
        pub genres: Vec<String>,
        pub id: String,
        pub kind: String,
        pub metadata_languages: Vec<String>,
        pub name: String,
        pub overview: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub release_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        pub slug: String,
        pub sort_name: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tmdb_id: Option<i64>,
        pub updated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleDetail {
        pub artwork: Vec<Artwork>,
        pub episode_progress: BTreeMap<String, EpisodeProgress>,
        pub in_watchlist: bool,
        pub media_files: Vec<MediaFile>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub progress: Option<EpisodeProgress>,
        pub seasons: Vec<Season>,
        pub title: Title,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleInput {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub content_rating: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub genres: Option<Vec<String>>,
        pub kind: TitleInputKind,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub metadata_languages: Option<Vec<String>>,
        pub name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum TitleInputKind {
        #[serde(rename = "movie")]
        Movie,
        #[serde(rename = "series")]
        Series,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl TitleInputKind {
        pub fn as_str(self) -> &'static str {
            match self {
                TitleInputKind::Movie => "movie",
                TitleInputKind::Series => "series",
                TitleInputKind::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for TitleInputKind {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleStorageBreakdown {
        pub items: Vec<StorageSegment>,
        pub source_bytes: i64,
        pub transcoded_bytes: i64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct TitleUpdate {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub allow_random_playback: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub content_rating: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub genres: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub metadata_languages: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub runtime_minutes: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub sort_name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub status: Option<TitleUpdateStatus>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tmdb_id: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub year: Option<i64>,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
    pub enum TitleUpdateStatus {
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "processing")]
        Processing,
        #[serde(rename = "published")]
        Published,
        #[serde(rename = "hidden")]
        Hidden,
        /// A value this client does not know yet.
        #[serde(other)]
        Unknown,
    }

    impl TitleUpdateStatus {
        pub fn as_str(self) -> &'static str {
            match self {
                TitleUpdateStatus::Draft => "draft",
                TitleUpdateStatus::Processing => "processing",
                TitleUpdateStatus::Published => "published",
                TitleUpdateStatus::Hidden => "hidden",
                TitleUpdateStatus::Unknown => "unknown",
            }
        }
    }

    impl std::fmt::Display for TitleUpdateStatus {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(self.as_str())
        }
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Translation {
        pub name: String,
        pub overview: String,
    }
}

pub mod ops {
    #![allow(clippy::doc_markdown, clippy::too_many_lines, clippy::wildcard_imports)]
    use super::types::*;
    use crate::{Call, Method, NoContent, Request, build};
    use std::collections::BTreeMap;

    /// `PUT /me/watchlist/{titleId}`
    pub fn add_to_watchlist(title_id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Put,
            format!("/me/watchlist/{}", build::segment(title_id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/uploads/{id}`
    pub fn admin_abort_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/uploads/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PUT /admin/uploads/{id}`
    pub fn admin_append_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Put,
            "/admin/uploads/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/titles/{id}/metadata/apply`
    pub fn admin_apply_metadata() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/titles/{id}/metadata/apply".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/titles/bulk`
    pub fn admin_bulk_titles(body: &BulkInputBody) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Post,
            "/admin/titles/bulk".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/jobs/{id}/cancel`
    pub fn admin_cancel_job() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/jobs/{id}/cancel".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/uploads/{id}/complete`
    pub fn admin_complete_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/uploads/{id}/complete".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/seasons/{id}/episodes`
    pub fn admin_create_episode(id: &str, body: &EpisodeInput) -> Call<Episode> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            format!("/admin/seasons/{}/episodes", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/titles/{id}/seasons`
    pub fn admin_create_season(id: &str, body: &CreateSeasonInputBody) -> Call<Season> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            format!("/admin/titles/{}/seasons", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/titles`
    pub fn admin_create_title(body: &TitleInput) -> Call<Title> {
        let q = Vec::new();
        build::json(build::request(
            Method::Post,
            "/admin/titles".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /admin/uploads`
    pub fn admin_create_upload() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/admin/uploads".to_string(), q, None::<&()>)
    }

    /// `POST /admin/users`
    pub fn admin_create_user() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/admin/users".to_string(), q, None::<&()>)
    }

    /// `DELETE /admin/artwork/{id}`
    pub fn admin_delete_artwork() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/artwork/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/episodes/{id}`
    pub fn admin_delete_episode(id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/episodes/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/media-files/{id}`
    pub fn admin_delete_media_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/media-files/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/seasons/{id}`
    pub fn admin_delete_season(id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/seasons/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/subtitles/{id}`
    pub fn admin_delete_subtitle() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/subtitles/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/titles/{id}`
    pub fn admin_delete_title(id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/admin/titles/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/titles/{id}/languages/{lang}`
    pub fn admin_delete_title_language(id: &str, lang: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!(
                "/admin/titles/{}/languages/{}",
                build::segment(id),
                build::segment(lang)
            ),
            q,
            None::<&()>,
        ))
    }

    /// `DELETE /admin/users/{id}`
    pub fn admin_delete_user() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/users/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /admin/transcode-variants/{id}`
    pub fn admin_delete_variant() -> Request {
        let q = Vec::new();
        build::request(
            Method::Delete,
            "/admin/transcode-variants/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/media-files/{id}/transcode`
    pub fn admin_enqueue_transcode() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/media-files/{id}/transcode".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/analytics/overview`
    pub fn admin_get_analytics() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/analytics/overview".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/episodes/{id}/translations`
    pub fn admin_get_episode_translations(id: &str) -> Call<BTreeMap<String, Translation>> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            format!("/admin/episodes/{}/translations", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/home-rows`
    pub fn admin_get_home_rows() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/home-rows".to_string(), q, None::<&()>)
    }

    /// `GET /admin/live`
    pub fn admin_get_live() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/live".to_string(), q, None::<&()>)
    }

    /// `GET /admin/overview`
    pub fn admin_get_overview() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/overview".to_string(), q, None::<&()>)
    }

    /// `GET /admin/ranks`
    pub fn admin_get_ranks() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/ranks".to_string(), q, None::<&()>)
    }

    /// `GET /admin/settings`
    pub fn admin_get_settings() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/settings".to_string(), q, None::<&()>)
    }

    /// `GET /admin/storage`
    pub fn admin_get_storage() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/storage".to_string(), q, None::<&()>)
    }

    /// `GET /admin/system`
    pub fn admin_get_system_stats() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/system".to_string(), q, None::<&()>)
    }

    /// `GET /admin/titles/{id}`
    pub fn admin_get_title(id: &str) -> Call<AdminTitle> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            format!("/admin/titles/{}", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/titles/{id}/storage`
    pub fn admin_get_title_storage(id: &str) -> Call<TitleStorageBreakdown> {
        let q = Vec::new();
        build::json(build::request(
            Method::Get,
            format!("/admin/titles/{}/storage", build::segment(id)),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/transcode/info`
    pub fn admin_get_transcode_info() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/transcode/info".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/uploads/{id}`
    pub fn admin_get_upload() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/uploads/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/titles/{id}/metadata/import-episodes`
    pub fn admin_import_episodes() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/titles/{id}/metadata/import-episodes".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/transcode/active`
    pub fn admin_list_active_transcodes() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/transcode/active".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/jobs`
    pub fn admin_list_jobs() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/jobs".to_string(), q, None::<&()>)
    }

    /// Query parameters of [`admin_list_library`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct AdminListLibraryQuery {
        pub r#type: Option<AdminListLibraryType>,
        pub status: Option<AdminListLibraryStatus>,
        pub q: Option<String>,
        pub sort: Option<AdminListLibrarySort>,
        pub page: Option<i64>,
        pub page_size: Option<i64>,
    }

    /// `GET /admin/library`
    pub fn admin_list_library(query: &AdminListLibraryQuery) -> Call<LibraryPage> {
        let mut q = Vec::new();
        build::push(&mut q, "type", query.r#type.as_ref());
        build::push(&mut q, "status", query.status.as_ref());
        build::push(&mut q, "q", query.q.as_ref());
        build::push(&mut q, "sort", query.sort.as_ref());
        build::push(&mut q, "page", query.page.as_ref());
        build::push(&mut q, "pageSize", query.page_size.as_ref());
        build::json(build::request(
            Method::Get,
            "/admin/library".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /admin/titles/{id}/metadata/seasons`
    pub fn admin_list_metadata_seasons() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/titles/{id}/metadata/seasons".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/media-files/{id}/subtitles`
    pub fn admin_list_subtitles() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/media-files/{id}/subtitles".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/uploads`
    pub fn admin_list_uploads() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/uploads".to_string(), q, None::<&()>)
    }

    /// `GET /admin/users`
    pub fn admin_list_users() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/admin/users".to_string(), q, None::<&()>)
    }

    /// `GET /admin/media-files/{id}/variants`
    pub fn admin_list_variants() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/media-files/{id}/variants".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/jobs/{id}/retry`
    pub fn admin_retry_job() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/jobs/{id}/retry".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /admin/metadata/search`
    pub fn admin_search_metadata() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/admin/metadata/search".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PATCH /admin/episodes/{id}/translations/{lang}`
    pub fn admin_set_episode_translation(
        id: &str,
        lang: &str,
        body: &Translation,
    ) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Patch,
            format!(
                "/admin/episodes/{}/translations/{}",
                build::segment(id),
                build::segment(lang)
            ),
            q,
            Some(body),
        ))
    }

    /// `PATCH /admin/titles/{id}/translations/{lang}`
    pub fn admin_set_title_translation(
        id: &str,
        lang: &str,
        body: &Translation,
    ) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Patch,
            format!(
                "/admin/titles/{}/translations/{}",
                build::segment(id),
                build::segment(lang)
            ),
            q,
            Some(body),
        ))
    }

    /// `PATCH /admin/episodes/{id}`
    pub fn admin_update_episode(id: &str, body: &EpisodeUpdate) -> Call<Episode> {
        let q = Vec::new();
        build::json(build::request(
            Method::Patch,
            format!("/admin/episodes/{}", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `PUT /admin/home-rows`
    pub fn admin_update_home_rows() -> Request {
        let q = Vec::new();
        build::request(Method::Put, "/admin/home-rows".to_string(), q, None::<&()>)
    }

    /// `PATCH /admin/media-files/{id}`
    pub fn admin_update_media_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Patch,
            "/admin/media-files/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PUT /admin/ranks/config`
    pub fn admin_update_ranks_config() -> Request {
        let q = Vec::new();
        build::request(
            Method::Put,
            "/admin/ranks/config".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `PUT /admin/settings`
    pub fn admin_update_settings() -> Request {
        let q = Vec::new();
        build::request(Method::Put, "/admin/settings".to_string(), q, None::<&()>)
    }

    /// `PATCH /admin/titles/{id}`
    pub fn admin_update_title(id: &str, body: &TitleUpdate) -> Call<Title> {
        let q = Vec::new();
        build::json(build::request(
            Method::Patch,
            format!("/admin/titles/{}", build::segment(id)),
            q,
            Some(body),
        ))
    }

    /// `PATCH /admin/users/{id}`
    pub fn admin_update_user() -> Request {
        let q = Vec::new();
        build::request(
            Method::Patch,
            "/admin/users/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /admin/artwork`
    pub fn admin_upload_artwork() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/admin/artwork".to_string(), q, None::<&()>)
    }

    /// `POST /admin/media-files/{id}/subtitles`
    pub fn admin_upload_subtitle() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/admin/media-files/{id}/subtitles".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`browse_titles`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct BrowseTitlesQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
        /// Only movies or only series; all when omitted.
        pub kind: Option<BrowseTitlesKind>,
        /// English genre name (the genre's stable identity).
        pub genre: Option<String>,
        /// Case-insensitive name filter.
        pub q: Option<String>,
        /// Ordering; newest first when omitted.
        pub sort: Option<BrowseTitlesSort>,
        pub page: Option<i64>,
    }

    /// `GET /titles`
    pub fn browse_titles(query: &BrowseTitlesQuery) -> Call<BrowsePage> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::push(&mut q, "kind", query.kind.as_ref());
        build::push(&mut q, "genre", query.genre.as_ref());
        build::push(&mut q, "q", query.q.as_ref());
        build::push(&mut q, "sort", query.sort.as_ref());
        build::push(&mut q, "page", query.page.as_ref());
        build::json(build::request(
            Method::Get,
            "/titles".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `PATCH /me/password`
    pub fn change_password() -> Request {
        let q = Vec::new();
        build::request(Method::Patch, "/me/password".to_string(), q, None::<&()>)
    }

    /// `POST /me/achievements/check`
    pub fn check_achievements() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/me/achievements/check".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /couch/{token}/ws`
    pub fn couch_socket() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/couch/{token}/ws".to_string(), q, None::<&()>)
    }

    /// `POST /couch`
    pub fn create_couch() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/couch".to_string(), q, None::<&()>)
    }

    /// `POST /stream/{id}/sessions`
    pub fn create_stream_session() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/stream/{id}/sessions".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `DELETE /me/avatar`
    pub fn delete_avatar() -> Request {
        let q = Vec::new();
        build::request(Method::Delete, "/me/avatar".to_string(), q, None::<&()>)
    }

    /// `DELETE /me/banner`
    pub fn delete_banner() -> Request {
        let q = Vec::new();
        build::request(Method::Delete, "/me/banner".to_string(), q, None::<&()>)
    }

    /// `POST /couch/{token}/end`
    pub fn end_couch() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/couch/{token}/end".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /artwork/{id}`
    pub fn get_artwork() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/artwork/{id}".to_string(), q, None::<&()>)
    }

    /// `GET /couch/{token}/info`
    pub fn get_couch_info() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/couch/{token}/info".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /couch/{token}/playback`
    pub fn get_couch_playback() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/couch/{token}/playback".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /features`
    pub fn get_features() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/features".to_string(), q, None::<&()>)
    }

    /// `GET /stream/{id}/hls/{variant}/{file}`
    pub fn get_hls_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/{id}/hls/{variant}/{file}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /stream/{id}/hls/master.m3u8`
    pub fn get_hls_master() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/{id}/hls/master.m3u8".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`get_home`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetHomeQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /home`
    pub fn get_home(query: &GetHomeQuery) -> Call<Home> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/home".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /leaderboard`
    pub fn get_leaderboard() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/leaderboard".to_string(), q, None::<&()>)
    }

    /// `GET /auth/me`
    pub fn get_me() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/auth/me".to_string(), q, None::<&()>)
    }

    /// `GET /me/stats`
    pub fn get_my_stats() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/me/stats".to_string(), q, None::<&()>)
    }

    /// `GET /playback/{kind}/{id}`
    pub fn get_playback() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/playback/{kind}/{id}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /me/preferences`
    pub fn get_preferences() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/me/preferences".to_string(), q, None::<&()>)
    }

    /// `GET /users/{username}/profile`
    pub fn get_profile() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/users/{username}/profile".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /stream/{id}/frame`
    pub fn get_stream_frame() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/{id}/frame".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /stream/sessions/{sid}/{file}`
    pub fn get_stream_session_file() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/stream/sessions/{sid}/{file}".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /subtitles/{id}.vtt`
    pub fn get_subtitle() -> Request {
        let q = Vec::new();
        build::request(
            Method::Get,
            "/subtitles/{id}.vtt".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `GET /theme`
    pub fn get_theme() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/theme".to_string(), q, None::<&()>)
    }

    /// Query parameters of [`get_title`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct GetTitleQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /titles/{slug}`
    pub fn get_title(slug: &str, query: &GetTitleQuery) -> Call<TitleDetail> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            format!("/titles/{}", build::segment(slug)),
            q,
            None::<&()>,
        ))
    }

    /// `POST /couch/{token}/join`
    pub fn join_couch() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/couch/{token}/join".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /stream/sessions/{sid}/keepalive`
    pub fn keep_stream_session_alive() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/stream/sessions/{sid}/keepalive".to_string(),
            q,
            None::<&()>,
        )
    }

    /// `POST /couch/{token}/leave`
    pub fn leave_couch() -> Request {
        let q = Vec::new();
        build::request(
            Method::Post,
            "/couch/{token}/leave".to_string(),
            q,
            None::<&()>,
        )
    }

    /// Query parameters of [`list_continue_watching`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct ListContinueWatchingQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /me/continue-watching`
    pub fn list_continue_watching(query: &ListContinueWatchingQuery) -> Call<Vec<ContinueItem>> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/me/continue-watching".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`list_genres`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct ListGenresQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /genres`
    pub fn list_genres(query: &ListGenresQuery) -> Call<Vec<Genre>> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/genres".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// Query parameters of [`list_watchlist`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct ListWatchlistQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
    }

    /// `GET /me/watchlist`
    pub fn list_watchlist(query: &ListWatchlistQuery) -> Call<Vec<CardItem>> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::json(build::request(
            Method::Get,
            "/me/watchlist".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `POST /auth/login`
    pub fn login() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/auth/login".to_string(), q, None::<&()>)
    }

    /// `POST /auth/logout`
    pub fn logout() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/auth/logout".to_string(), q, None::<&()>)
    }

    /// `DELETE /me/watchlist/{titleId}`
    pub fn remove_from_watchlist(title_id: &str) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Delete,
            format!("/me/watchlist/{}", build::segment(title_id)),
            q,
            None::<&()>,
        ))
    }

    /// `PUT /progress`
    pub fn save_progress(body: &ProgressReport) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Put,
            "/progress".to_string(),
            q,
            Some(body),
        ))
    }

    /// `POST /progress`
    pub fn save_progress_beacon(body: &ProgressReport) -> Call<NoContent> {
        let q = Vec::new();
        build::no_content(build::request(
            Method::Post,
            "/progress".to_string(),
            q,
            Some(body),
        ))
    }

    /// Query parameters of [`search`].
    #[derive(Debug, Clone, Default, PartialEq)]
    pub struct SearchQuery {
        /// Display language (ISO 639-1). Empty serves the base text.
        pub lang: Option<String>,
        pub q: Option<String>,
    }

    /// `GET /search`
    pub fn search(query: &SearchQuery) -> Call<SearchResults> {
        let mut q = Vec::new();
        build::push(&mut q, "lang", query.lang.as_ref());
        build::push(&mut q, "q", query.q.as_ref());
        build::json(build::request(
            Method::Get,
            "/search".to_string(),
            q,
            None::<&()>,
        ))
    }

    /// `GET /stream/{id}`
    pub fn stream_media_file() -> Request {
        let q = Vec::new();
        build::request(Method::Get, "/stream/{id}".to_string(), q, None::<&()>)
    }

    /// `PUT /me/preferences`
    pub fn update_preferences() -> Request {
        let q = Vec::new();
        build::request(Method::Put, "/me/preferences".to_string(), q, None::<&()>)
    }

    /// `PATCH /me/profile`
    pub fn update_profile() -> Request {
        let q = Vec::new();
        build::request(Method::Patch, "/me/profile".to_string(), q, None::<&()>)
    }

    /// `POST /me/avatar`
    pub fn upload_avatar() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/me/avatar".to_string(), q, None::<&()>)
    }

    /// `POST /me/banner`
    pub fn upload_banner() -> Request {
        let q = Vec::new();
        build::request(Method::Post, "/me/banner".to_string(), q, None::<&()>)
    }
}
