//! Locations and writing of generated files.

use std::fs;
use std::path::{Path, PathBuf};

/// Header for generated source files; `comment` is the language's line-comment prefix.
pub fn header(comment: &str, source: &str) -> String {
    format!("{comment} Generated by `cargo xtask codegen` from {source}. Do not edit.\n")
}

pub fn repo_root() -> PathBuf {
    // xtask lives at core/xtask
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("xtask is two levels below the repository root")
        .to_path_buf()
}

/// Writes `contents` to `path` (creating directories) unless it is already up to date, and
/// records the path when it changed so `codegen` can report it.
pub fn write(path: &Path, contents: &str, written: &mut Vec<PathBuf>) -> Result<(), String> {
    if fs::read_to_string(path).is_ok_and(|current| current == contents) {
        return Ok(());
    }
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
    }
    fs::write(path, contents).map_err(|e| format!("write {}: {e}", path.display()))?;
    written.push(path.to_path_buf());
    Ok(())
}

pub fn read_json(path: &Path) -> Result<serde_json::Value, String> {
    let text = fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_str(&text).map_err(|e| format!("parse {}: {e}", path.display()))
}

/// `catalog_season_count` -> `catalogSeasonCount`, `surface-2` -> `surface2`.
pub fn camel(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper = false;
    for c in name.chars() {
        if c == '_' || c == '-' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}
