//! Packaging the core for each shell (plan 7.7): the xcframework and Swift bindings for Apple,
//! the per-ABI libraries and Kotlin bindings for Android, the wasm package for the web. All of it
//! is build output and gitignored; the message types the shells decode are generated by
//! `codegen` and committed.

use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::out;

const FFI: &str = "couchverse-ffi";
const LIB: &str = "libcouchverse_ffi";
const APPLE_TARGETS: [&str; 5] = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-apple-tvos",
    "aarch64-apple-tvos-sim",
    // for `swift test` on the host
    "aarch64-apple-darwin",
];
const APPLE_PACKAGE: &str = "clients/apple/Packages/CouchverseCore";
const ANDROID_ABIS: [&str; 3] = ["arm64-v8a", "armeabi-v7a", "x86_64"];
const ANDROID_MODULE: &str = "clients/android/core";
const WASM_PACKAGE: &str = "clients/web/src/lib/core/pkg";
/// Plan 7.7: every web visitor downloads the core (once; it is cached after that).
const WASM_BUDGET_GZIP: usize = 400 * 1024;

pub fn apple() -> Result<(), String> {
    let root = out::repo_root();
    let core = root.join("core");
    // one target at a time: parallel builds only queue on the build-dir lock
    for target in APPLE_TARGETS {
        cargo(&core, &["build", "-p", FFI, "--release", "--target", target])?;
    }

    let staging = core.join("target/apple");
    let include = staging.join("include/CouchverseCoreFFI");
    reset_dir(&staging)?;
    fs::create_dir_all(&include).map_err(|e| format!("create {}: {e}", include.display()))?;
    // library mode reads the interface from the compiled library, so the bindings always match
    // the slices built above (UniFFI checks API checksums on the first call); no
    // `--xcframework`, whose `framework module` map cannot be imported from a library slice
    let host_lib = core.join(format!("target/aarch64-apple-darwin/release/{LIB}.a"));
    cargo(
        &core,
        &[
            "run",
            "-q",
            "-p",
            "couchverse-uniffi-bindgen",
            "--bin",
            "uniffi-bindgen-swift",
            "--",
            "--swift-sources",
            "--headers",
            "--modulemap",
            "--module-name",
            "CouchverseCoreFFI",
            "--modulemap-filename",
            "module.modulemap",
            path_str(&host_lib)?,
            path_str(&staging.join("bindings"))?,
        ],
    )?;
    // Xcode merges every xcframework's Headers/ into one directory, so the module map lives in a
    // directory named after the module instead of colliding at the top level
    for file in ["CouchverseCoreFFI.h", "module.modulemap"] {
        copy(&staging.join("bindings").join(file), &include.join(file))?;
    }

    let package = root.join(APPLE_PACKAGE);
    let framework = package.join("CouchverseCoreFFI.xcframework");
    if framework.exists() {
        fs::remove_dir_all(&framework)
            .map_err(|e| format!("remove {}: {e}", framework.display()))?;
    }
    let mut xcodebuild = Command::new("xcodebuild");
    xcodebuild.arg("-create-xcframework");
    for target in APPLE_TARGETS {
        xcodebuild
            .arg("-library")
            .arg(core.join(format!("target/{target}/release/{LIB}.a")))
            .arg("-headers")
            .arg(staging.join("include"));
    }
    xcodebuild.arg("-output").arg(&framework);
    run(&mut xcodebuild)?;

    let ffi_sources = package.join("Sources/CouchverseCore/FFI");
    reset_dir(&ffi_sources)?;
    copy(
        &staging.join("bindings/CouchverseCore.swift"),
        &ffi_sources.join("CouchverseCore.swift"),
    )?;
    println!("built {}", framework.strip_prefix(&root).unwrap_or(&framework).display());
    Ok(())
}

pub fn android() -> Result<(), String> {
    let root = out::repo_root();
    let core = root.join("core");
    let module = root.join(ANDROID_MODULE);
    let jni_libs = module.join("src/main/jniLibs");

    let mut ndk = Command::new("cargo");
    ndk.current_dir(&core).arg("ndk");
    for abi in ANDROID_ABIS {
        ndk.args(["-t", abi]);
    }
    // API 31 is the app's minSdk; cargo-ndk also aligns the libraries for 16 KB pages
    ndk.args(["--platform", "31", "-o"]).arg(&jni_libs).args(["build", "--release", "-p", FFI]);
    if std::env::var_os("ANDROID_NDK_HOME").is_none()
        && let Some(home) = default_ndk()
    {
        ndk.env("ANDROID_NDK_HOME", home);
    }
    run(&mut ndk).map_err(|e| {
        format!("{e}\n(needs `cargo install cargo-ndk`, the Android NDK and its rustup targets)")
    })?;

    // the host library serves the JVM unit tests through JNA and is the bindings' source
    cargo(&core, &["build", "-p", FFI, "--release"])?;
    let host_lib = core.join(format!("target/release/{LIB}.{}", host_dylib_extension()));
    let host_dir = module.join("build/rust-host");
    reset_dir(&host_dir)?;
    copy(&host_lib, &host_dir.join(host_lib.file_name().expect("library file name")))?;

    let bindings = module.join("build/generated/uniffi");
    reset_dir(&bindings)?;
    cargo(
        &core,
        &[
            "run",
            "-q",
            "-p",
            "couchverse-uniffi-bindgen",
            "--bin",
            "uniffi-bindgen",
            "--",
            "generate",
            "--library",
            path_str(&host_lib)?,
            "--language",
            "kotlin",
            "--out-dir",
            path_str(&bindings)?,
            "--no-format",
        ],
    )?;
    println!("built {}", jni_libs.strip_prefix(&root).unwrap_or(&jni_libs).display());
    Ok(())
}

pub fn wasm() -> Result<(), String> {
    let root = out::repo_root();
    let core = root.join("core");
    cargo(
        &core,
        &[
            "build",
            "-p",
            "couchverse-wasm",
            "--profile",
            "release-wasm",
            "--target",
            "wasm32-unknown-unknown",
        ],
    )?;
    let input = core.join("target/wasm32-unknown-unknown/release-wasm/couchverse_wasm.wasm");
    let package = root.join(WASM_PACKAGE);
    reset_dir(&package)?;
    wasm_bindgen_cli_support::Bindgen::new()
        .input_path(&input)
        .out_name("couchverse_core")
        .typescript(true)
        .web(true)
        .and_then(|b| b.generate(&package))
        .map_err(|e| format!("wasm-bindgen: {e:#}"))?;

    let wasm = package.join("couchverse_core_bg.wasm");
    // optional locally, required in CI and the image, where size counts
    match Command::new("wasm-opt").arg("--version").output() {
        Ok(_) => run(Command::new("wasm-opt")
            .args(["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"])
            .args(["--enable-sign-ext", "--enable-mutable-globals", "--enable-reference-types"])
            .arg("--enable-multivalue")
            .arg(&wasm)
            .arg("-o")
            .arg(&wasm))?,
        Err(_) if std::env::var_os("CI").is_some() => {
            return Err("wasm-opt (binaryen) is required in CI".into());
        }
        Err(_) => eprintln!("warning: wasm-opt not found, the package is unoptimized"),
    }

    let bytes = fs::read(&wasm).map_err(|e| format!("read {}: {e}", wasm.display()))?;
    let gzip = gzip_size(&bytes)?;
    println!(
        "built {} ({} KB, {} KB gzip)",
        package.strip_prefix(&root).unwrap_or(&package).display(),
        bytes.len() / 1024,
        gzip / 1024
    );
    if gzip > WASM_BUDGET_GZIP {
        return Err(format!(
            "the wasm core is {gzip} bytes gzipped, over the {WASM_BUDGET_GZIP} budget"
        ));
    }
    Ok(())
}

fn gzip_size(bytes: &[u8]) -> Result<usize, String> {
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
    encoder.write_all(bytes).map_err(|e| e.to_string())?;
    Ok(encoder.finish().map_err(|e| e.to_string())?.len())
}

/// The newest NDK under the default SDK locations, for machines without `ANDROID_NDK_HOME`.
fn default_ndk() -> Option<PathBuf> {
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let sdks = [
        std::env::var_os("ANDROID_HOME").map(PathBuf::from),
        Some(home.join("Library/Android/sdk")),
        Some(home.join("Android/Sdk")),
    ];
    sdks.into_iter()
        .flatten()
        .filter_map(|sdk| fs::read_dir(sdk.join("ndk")).ok())
        .find_map(|entries| entries.filter_map(Result::ok).map(|e| e.path()).max())
}

fn host_dylib_extension() -> &'static str {
    if cfg!(target_os = "macos") { "dylib" } else { "so" }
}

fn cargo(dir: &Path, args: &[&str]) -> Result<(), String> {
    run(Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .current_dir(dir)
        .args(args))
}

fn run(command: &mut Command) -> Result<(), String> {
    let status = command.status().map_err(|e| format!("{command:?}: {e}"))?;
    if status.success() { Ok(()) } else { Err(format!("{command:?} failed: {status}")) }
}

fn reset_dir(dir: &Path) -> Result<(), String> {
    if dir.exists() {
        fs::remove_dir_all(dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
    }
    fs::create_dir_all(dir).map_err(|e| format!("create {}: {e}", dir.display()))
}

fn copy(from: &Path, to: &Path) -> Result<(), String> {
    fs::copy(from, to)
        .map(drop)
        .map_err(|e| format!("copy {} to {}: {e}", from.display(), to.display()))
}

fn path_str(path: &Path) -> Result<&str, String> {
    path.to_str().ok_or_else(|| format!("{} is not UTF-8", path.display()))
}
